<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Veterinaria.Application\Veterinaria.Application.csproj" />
    <ProjectReference Include="..\Veterinaria.Domain\Veterinaria.Domain.csproj" />
  </ItemGroup>
</Project>
