CREATE DATABASE IF NOT EXISTS veterinaria_db;
USE veterinaria_db;

CREATE TABLE IF NOT EXISTS Duenos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(20),
    email VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Mascotas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    especie VARCHAR(50) NOT NULL,
    raza VARCHAR(50),
    dueno_id INT NOT NULL,
    FOREIGN KEY (dueno_id) REFERENCES Duenos(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Citas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fecha_hora DATETIME NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    estado VARCHAR(50) NOT NULL,
    mascota_id INT NOT NULL,
    FOREIGN KEY (mascota_id) REFERENCES Mascotas(id) ON DELETE CASCADE
);
